name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pelican[markdown] typogrify
          pip install linkchecker

      - name: Build site
        run: pelican content -o output -s publishconf.py

      - name: Run link checker
        run: linkchecker output/index.html --ignore-url "https://quang-ng.github.io/getpelican-cmn" --quiet

      - name: Deploy to GitHub Pages
        uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
        permissions:
          contents: "read"
          pages: "write"
          id-token: "write"
        with:
          settings: "publishconf.py"  
          requirements: "pelican[markdown] typogrify"
          python: "3.12"
          feed_domain: "https://quang-ng.github.io/getpelican-cmn"
          siteurl: "https://quang-ng.github.io/getpelican-cmn"